trigger:
  - trunk
stages:
- stage: build
  jobs:
  - job: build_all
    pool:
      vmImage: 'windows-latest'
    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: "12.x"
      displayName: 'set node environment'

    - script: |
        npm i && npm run build
      displayName: build client app
      workingDirectory: monolith.app/ClientApp      
        
    - template: 'monolith.pipelines/templates/dotnetbuild.yml'
      parameters:
        configuration: 'release'
        artifactName: 'monolithapp'
        framework: 'netcoreapp3.1'
    
    - template: 'monolith.pipelines/templates/dotnettest.yml'
      parameters:
        configuration: 'release'


    - task: CopyFiles@2
      displayName: Copy ClientLib to output assembly folder
      inputs:
        targetFolder: monolith.app/bin/release/netcoreapp3.1/ClientApp/dist
        sourceFolder: monolith.app/ClientApp/dist    
        
    - task: ArchiveFiles@2
      displayName: bundle
      inputs:
        rootFolderOrFile: monolith.app/bin/release/netcoreapp3.1
        includeRootFolder: false
        archiveFile: 'monolithapp'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: monolith.app/bin/release/netcoreapp3.1
        ArtifactName: 'momolithapp'     

    - task: PublishBuildArtifacts@1
      displayName: 'publish infra scripts'
      inputs:
        PathToPublish: 'monolith.infra'
        ArtifactName: infra
- stage: deploy
  jobs:
  - deployment: 'production'
    pool:
      vmImage: 'windows-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            displayName: download infra
            artifact: 'infra'

          - template: 'monolith.pipelines/templates/infra.yml'
            parameters:
              principal: '$(principal)'
              resourceGroup: 'monolith'
              region: 'northcentralus'
              templatepath: 'infra/keyvault/keyvault.json'
              parameterspath: 'infra/keyvault/keyvaultparams.json'
          
          - template: 'monolith.pipelines/templates/infra.yml'
            parameters:
              principal: '$(principal)'
              resourceGroup: 'monolith'
              region: 'northcentralus'
              templatepath: 'infra/insights/insights.json'
              parameterspath: 'infra/insights/insightsparams.json'

          - template: 'monolith.pipelines/templates/infra.yml'
            parameters:
              principal: '$(principal)'
              resourceGroup: 'monolith'
              region: 'northcentralus'
              templatepath: 'infra/app/app.json'
              parameterspath: 'infra/app/appparams.json'

          - template: 'monolith.pipelines/templates/download-and-deploy.yml'
            parameters: 
              appType: app
              artifact: monolithapp
              principal: '$(principal)'
              appName: brgs-monolith

          
          
